/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Connection.Conexao;
import com.sun.jdi.connect.spi.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author gabri
 */
public class NovoEmprestimo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NovoEmprestimo.class.getName());

    /**
     * Creates new form NovoEmprestimo
     */
    public NovoEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        bntBuscarUsuario = new javax.swing.JButton();
        lblNomeUsuario = new javax.swing.JLabel();
        lblTipoUsario = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        txtIdMaterial = new javax.swing.JTextField();
        bntBuscarMaterial = new javax.swing.JButton();
        lblTituloMaterial = new javax.swing.JLabel();
        lblDisponivel = new javax.swing.JLabel();
        lblDataEmprestimo = new javax.swing.JLabel();
        txtDataEmprestimo = new javax.swing.JFormattedTextField();
        lblDataPrevista = new javax.swing.JLabel();
        txtDataPrevista = new javax.swing.JFormattedTextField();
        bntCalendario = new javax.swing.JButton();
        lblObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        bntRegistrar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Novo Empréstimo");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setText("Usuário: ");

        bntBuscarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntBuscarUsuario.setText("Buscar Usuário");
        bntBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarUsuarioActionPerformed(evt);
            }
        });

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNomeUsuario.setText("Nome: ");

        lblTipoUsario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoUsario.setText("Tipo:");

        lblMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaterial.setText("Material:");

        txtIdMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMaterialActionPerformed(evt);
            }
        });

        bntBuscarMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntBuscarMaterial.setText("Buscar Material");
        bntBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarMaterialActionPerformed(evt);
            }
        });

        lblTituloMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblDisponivel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblDataEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataEmprestimo.setText("Data de empréstimo: ");

        try {
            txtDataEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDataPrevista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataPrevista.setText("Data prevista: ");

        try {
            txtDataPrevista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataPrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPrevistaActionPerformed(evt);
            }
        });

        bntCalendario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCalendario.setText("Calendário");
        bntCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalendarioActionPerformed(evt);
            }
        });

        lblObs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblObs.setText("Observações:");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        bntRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntRegistrar.setText("Registrar");
        bntRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarActionPerformed(evt);
            }
        });

        bntCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoUsario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscarUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lblDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bntBuscarMaterial)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblDataEmprestimo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIdMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataPrevista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntCalendario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntRegistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntCancelar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntBuscarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoUsario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaterial)
                    .addComponent(txtIdMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntBuscarMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataEmprestimo)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPrevista)
                    .addComponent(txtDataPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCalendario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisponivel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(lblTituloMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObs)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRegistrar)
                    .addComponent(bntCancelar))
                .addGap(0, 114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        String idStr = txtIdUsuario.getText().trim();
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite o ID do usuário.");
        return;
    }
    try (Connection conn = Conexao.getConnection()) {
        String sql = "SELECT nome, tipo FROM Usuario WHERE id = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setInt(1, Integer.parseInt(idStr));
        ResultSet rs = st.executeQuery();
        if (rs.next()) {
            lblNomeUsuario.setText("Nome: " + rs.getString("nome"));
            lblTipoUsuario.setText("Tipo: " + rs.getString("tipo"));
        } else {
            JOptionPane.showMessageDialog(this, "Usuário não encontrado.");
            lblNomeUsuario.setText("Nome:");
            lblTipoUsuario.setText("Tipo:");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao buscar usuário: " + e.getMessage());
    }
    }//GEN-LAST:event_bntBuscarUsuarioActionPerformed

    private void txtIdMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMaterialActionPerformed

    private void bntBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarMaterialActionPerformed
        // TODO add your handling code here:
        String idStr = txtIdMaterial.getText().trim();
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite o ID do material.");
        return;
    }
    try (Connection conn = Conexao.getConnection()) {
        String sql = "SELECT titulo, quantidade FROM Material WHERE id = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setInt(1, Integer.parseInt(idStr));
        ResultSet rs = st.executeQuery();
        if (rs.next()) {
            lblTituloMaterial.setText("Título: " + rs.getString("titulo"));
            int qtd = rs.getInt("quantidade");
            lblDisponivel.setText(qtd > 0 ? "Disponível: Sim (" + qtd + ")" : "Disponível: Não (0)");
        } else {
            JOptionPane.showMessageDialog(this, "Material não encontrado.");
            lblTituloMaterial.setText("Título:");
            lblDisponivel.setText("Disponível:");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao buscar material: " + e.getMessage());
    }
    }//GEN-LAST:event_bntBuscarMaterialActionPerformed

    private void txtDataPrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPrevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPrevistaActionPerformed

    private void bntCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalendarioActionPerformed
        // TODO add your handling code here:
        JDateChooser chooser = new JDateChooser();
    chooser.setDateFormatString("dd/MM/yyyy");
    int resp = JOptionPane.showConfirmDialog(this, chooser, "Selecione a data", JOptionPane.OK_CANCEL_OPTION);
    if (resp == JOptionPane.OK_OPTION) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txtDataPrevista.setText(sdf.format(chooser.getDate()));
    }
    }//GEN-LAST:event_bntCalendarioActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void bntRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarActionPerformed
        // TODO add your handling code here:
        String idUsuario = txtIdUsuario.getText().trim();
    String idMaterial = txtIdMaterial.getText().trim();
    String dataEmp = txtDataEmprestimo.getText().trim();
    String dataPrev = txtDataPrevista.getText().trim();
    String obs = txtObs.getText().trim();

    if (idUsuario.isEmpty() || idMaterial.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe usuário e material.");
        return;
    }

    String sql = "INSERT INTO Emprestimo (idUsuario, idMaterial, dataEmprestimo, dataPrevista, observacoes) VALUES (?, ?, ?, ?, ?)";
    try (Connection conn = Conexao.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, Integer.parseInt(idUsuario));
        ps.setInt(2, Integer.parseInt(idMaterial));
        ps.setString(3, dataEmp);
        ps.setString(4, dataPrev);
        ps.setString(5, obs);

        int n = ps.executeUpdate();
        if (n > 0) {
            JOptionPane.showMessageDialog(this, "Empréstimo registrado com sucesso!");
            this.dispose(); // fecha a tela
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao registrar empréstimo.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
    }//GEN-LAST:event_bntRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NovoEmprestimo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscarMaterial;
    private javax.swing.JButton bntBuscarUsuario;
    private javax.swing.JButton bntCalendario;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataEmprestimo;
    private javax.swing.JLabel lblDataPrevista;
    private javax.swing.JLabel lblDisponivel;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblTipoUsario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloMaterial;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JFormattedTextField txtDataEmprestimo;
    private javax.swing.JFormattedTextField txtDataPrevista;
    private javax.swing.JTextField txtIdMaterial;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextArea txtObs;
    // End of variables declaration//GEN-END:variables
}
